version: "3"

x-common-variables: &postgres-variables
  POSTGRES_DB: eth
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test

services:
  go-docker-image:
    depends_on:
      - database
    build: ./
    environment: *postgres-variables
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
  database:
    image: glassnode/code-challenge-2020-database:latest
    environment: *postgres-variables
    ports:
      - "5432:5432"
