version: "3"
services:
  go-docker-image:
    build: ./
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
  database:
    image: glassnode/code-challenge-2020-database:latest
    environment:
      POSTGRES_DB: eth
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
